/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedReadinessRouteImport } from './routes/_authenticated/readiness'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated/questions'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPlaygroundRouteImport } from './routes/_authenticated/playground'
import { Route as AuthenticatedMyScoresRouteImport } from './routes/_authenticated/my-scores'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedGradebookRouteImport } from './routes/_authenticated/gradebook'
import { Route as AuthenticatedEvaluateRouteImport } from './routes/_authenticated/evaluate'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCodingRouteImport } from './routes/_authenticated/coding'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedBatchesRouteImport } from './routes/_authenticated/batches'
import { Route as AuthenticatedAuthoringRouteImport } from './routes/_authenticated/authoring'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedTestsIndexRouteImport } from './routes/_authenticated/tests.index'
import { Route as AuthenticatedProblemsIndexRouteImport } from './routes/_authenticated/problems.index'
import { Route as AuthenticatedTestsTestIdRouteImport } from './routes/_authenticated/tests.$testId'
import { Route as AuthenticatedProblemsProfileRouteImport } from './routes/_authenticated/problems.profile'
import { Route as AuthenticatedProblemsSlugRouteImport } from './routes/_authenticated/problems.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedProblemsPlansIndexRouteImport } from './routes/_authenticated/problems.plans.index'
import { Route as AuthenticatedProblemsContestsIndexRouteImport } from './routes/_authenticated/problems.contests.index'
import { Route as AuthenticatedProblemsPlansSlugRouteImport } from './routes/_authenticated/problems.plans.$slug'
import { Route as AuthenticatedProblemsContestsSlugRouteImport } from './routes/_authenticated/problems.contests.$slug'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadinessRoute = AuthenticatedReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaygroundRoute = AuthenticatedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyScoresRoute = AuthenticatedMyScoresRouteImport.update({
  id: '/my-scores',
  path: '/my-scores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradebookRoute = AuthenticatedGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvaluateRoute = AuthenticatedEvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodingRoute = AuthenticatedCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchesRoute = AuthenticatedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuthoringRoute = AuthenticatedAuthoringRouteImport.update({
  id: '/authoring',
  path: '/authoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTestsIndexRoute = AuthenticatedTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemsIndexRoute =
  AuthenticatedProblemsIndexRouteImport.update({
    id: '/problems/',
    path: '/problems/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsTestIdRoute =
  AuthenticatedTestsTestIdRouteImport.update({
    id: '/tests/$testId',
    path: '/tests/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProblemsProfileRoute =
  AuthenticatedProblemsProfileRouteImport.update({
    id: '/problems/profile',
    path: '/problems/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProblemsSlugRoute =
  AuthenticatedProblemsSlugRouteImport.update({
    id: '/problems/$slug',
    path: '/problems/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProblemsPlansIndexRoute =
  AuthenticatedProblemsPlansIndexRouteImport.update({
    id: '/problems/plans/',
    path: '/problems/plans/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProblemsContestsIndexRoute =
  AuthenticatedProblemsContestsIndexRouteImport.update({
    id: '/problems/contests/',
    path: '/problems/contests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProblemsPlansSlugRoute =
  AuthenticatedProblemsPlansSlugRouteImport.update({
    id: '/problems/plans/$slug',
    path: '/problems/plans/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProblemsContestsSlugRoute =
  AuthenticatedProblemsContestsSlugRouteImport.update({
    id: '/problems/contests/$slug',
    path: '/problems/contests/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/verify': typeof VerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/authoring': typeof AuthenticatedAuthoringRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/coding': typeof AuthenticatedCodingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evaluate': typeof AuthenticatedEvaluateRoute
  '/gradebook': typeof AuthenticatedGradebookRoute
  '/import': typeof AuthenticatedImportRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/my-scores': typeof AuthenticatedMyScoresRoute
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/problems/$slug': typeof AuthenticatedProblemsSlugRoute
  '/problems/profile': typeof AuthenticatedProblemsProfileRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/problems/': typeof AuthenticatedProblemsIndexRoute
  '/tests/': typeof AuthenticatedTestsIndexRoute
  '/problems/contests/$slug': typeof AuthenticatedProblemsContestsSlugRoute
  '/problems/plans/$slug': typeof AuthenticatedProblemsPlansSlugRoute
  '/problems/contests/': typeof AuthenticatedProblemsContestsIndexRoute
  '/problems/plans/': typeof AuthenticatedProblemsPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/verify': typeof VerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/authoring': typeof AuthenticatedAuthoringRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/coding': typeof AuthenticatedCodingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evaluate': typeof AuthenticatedEvaluateRoute
  '/gradebook': typeof AuthenticatedGradebookRoute
  '/import': typeof AuthenticatedImportRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/my-scores': typeof AuthenticatedMyScoresRoute
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/problems/$slug': typeof AuthenticatedProblemsSlugRoute
  '/problems/profile': typeof AuthenticatedProblemsProfileRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/problems': typeof AuthenticatedProblemsIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/problems/contests/$slug': typeof AuthenticatedProblemsContestsSlugRoute
  '/problems/plans/$slug': typeof AuthenticatedProblemsPlansSlugRoute
  '/problems/contests': typeof AuthenticatedProblemsContestsIndexRoute
  '/problems/plans': typeof AuthenticatedProblemsPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/verify': typeof VerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/authoring': typeof AuthenticatedAuthoringRoute
  '/_authenticated/batches': typeof AuthenticatedBatchesRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/coding': typeof AuthenticatedCodingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evaluate': typeof AuthenticatedEvaluateRoute
  '/_authenticated/gradebook': typeof AuthenticatedGradebookRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/my-scores': typeof AuthenticatedMyScoresRoute
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/readiness': typeof AuthenticatedReadinessRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/problems/$slug': typeof AuthenticatedProblemsSlugRoute
  '/_authenticated/problems/profile': typeof AuthenticatedProblemsProfileRoute
  '/_authenticated/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/_authenticated/problems/': typeof AuthenticatedProblemsIndexRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexRoute
  '/_authenticated/problems/contests/$slug': typeof AuthenticatedProblemsContestsSlugRoute
  '/_authenticated/problems/plans/$slug': typeof AuthenticatedProblemsPlansSlugRoute
  '/_authenticated/problems/contests/': typeof AuthenticatedProblemsContestsIndexRoute
  '/_authenticated/problems/plans/': typeof AuthenticatedProblemsPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/achievements'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/assessments'
    | '/attendance'
    | '/authoring'
    | '/batches'
    | '/certificates'
    | '/coding'
    | '/dashboard'
    | '/evaluate'
    | '/gradebook'
    | '/import'
    | '/modules'
    | '/my-scores'
    | '/playground'
    | '/practice'
    | '/questions'
    | '/readiness'
    | '/resources'
    | '/roles'
    | '/schedule'
    | '/students'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/problems/$slug'
    | '/problems/profile'
    | '/tests/$testId'
    | '/problems/'
    | '/tests/'
    | '/problems/contests/$slug'
    | '/problems/plans/$slug'
    | '/problems/contests/'
    | '/problems/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/achievements'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/assessments'
    | '/attendance'
    | '/authoring'
    | '/batches'
    | '/certificates'
    | '/coding'
    | '/dashboard'
    | '/evaluate'
    | '/gradebook'
    | '/import'
    | '/modules'
    | '/my-scores'
    | '/playground'
    | '/practice'
    | '/questions'
    | '/readiness'
    | '/resources'
    | '/roles'
    | '/schedule'
    | '/students'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/problems/$slug'
    | '/problems/profile'
    | '/tests/$testId'
    | '/problems'
    | '/tests'
    | '/problems/contests/$slug'
    | '/problems/plans/$slug'
    | '/problems/contests'
    | '/problems/plans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/assessments'
    | '/_authenticated/attendance'
    | '/_authenticated/authoring'
    | '/_authenticated/batches'
    | '/_authenticated/certificates'
    | '/_authenticated/coding'
    | '/_authenticated/dashboard'
    | '/_authenticated/evaluate'
    | '/_authenticated/gradebook'
    | '/_authenticated/import'
    | '/_authenticated/modules'
    | '/_authenticated/my-scores'
    | '/_authenticated/playground'
    | '/_authenticated/practice'
    | '/_authenticated/questions'
    | '/_authenticated/readiness'
    | '/_authenticated/resources'
    | '/_authenticated/roles'
    | '/_authenticated/schedule'
    | '/_authenticated/students'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/problems/$slug'
    | '/_authenticated/problems/profile'
    | '/_authenticated/tests/$testId'
    | '/_authenticated/problems/'
    | '/_authenticated/tests/'
    | '/_authenticated/problems/contests/$slug'
    | '/_authenticated/problems/plans/$slug'
    | '/_authenticated/problems/contests/'
    | '/_authenticated/problems/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  VerifyRoute: typeof VerifyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/readiness': {
      id: '/_authenticated/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof AuthenticatedReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playground': {
      id: '/_authenticated/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-scores': {
      id: '/_authenticated/my-scores'
      path: '/my-scores'
      fullPath: '/my-scores'
      preLoaderRoute: typeof AuthenticatedMyScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gradebook': {
      id: '/_authenticated/gradebook'
      path: '/gradebook'
      fullPath: '/gradebook'
      preLoaderRoute: typeof AuthenticatedGradebookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluate': {
      id: '/_authenticated/evaluate'
      path: '/evaluate'
      fullPath: '/evaluate'
      preLoaderRoute: typeof AuthenticatedEvaluateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coding': {
      id: '/_authenticated/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof AuthenticatedCodingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches': {
      id: '/_authenticated/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/authoring': {
      id: '/_authenticated/authoring'
      path: '/authoring'
      fullPath: '/authoring'
      preLoaderRoute: typeof AuthenticatedAuthoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof AuthenticatedTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems/': {
      id: '/_authenticated/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof AuthenticatedProblemsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/$testId': {
      id: '/_authenticated/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AuthenticatedTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems/profile': {
      id: '/_authenticated/problems/profile'
      path: '/problems/profile'
      fullPath: '/problems/profile'
      preLoaderRoute: typeof AuthenticatedProblemsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems/$slug': {
      id: '/_authenticated/problems/$slug'
      path: '/problems/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof AuthenticatedProblemsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/problems/plans/': {
      id: '/_authenticated/problems/plans/'
      path: '/problems/plans'
      fullPath: '/problems/plans/'
      preLoaderRoute: typeof AuthenticatedProblemsPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems/contests/': {
      id: '/_authenticated/problems/contests/'
      path: '/problems/contests'
      fullPath: '/problems/contests/'
      preLoaderRoute: typeof AuthenticatedProblemsContestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems/plans/$slug': {
      id: '/_authenticated/problems/plans/$slug'
      path: '/problems/plans/$slug'
      fullPath: '/problems/plans/$slug'
      preLoaderRoute: typeof AuthenticatedProblemsPlansSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems/contests/$slug': {
      id: '/_authenticated/problems/contests/$slug'
      path: '/problems/contests/$slug'
      fullPath: '/problems/contests/$slug'
      preLoaderRoute: typeof AuthenticatedProblemsContestsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuthoringRoute: typeof AuthenticatedAuthoringRoute
  AuthenticatedBatchesRoute: typeof AuthenticatedBatchesRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedCodingRoute: typeof AuthenticatedCodingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvaluateRoute: typeof AuthenticatedEvaluateRoute
  AuthenticatedGradebookRoute: typeof AuthenticatedGradebookRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedMyScoresRoute: typeof AuthenticatedMyScoresRoute
  AuthenticatedPlaygroundRoute: typeof AuthenticatedPlaygroundRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
  AuthenticatedReadinessRoute: typeof AuthenticatedReadinessRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedProblemsSlugRoute: typeof AuthenticatedProblemsSlugRoute
  AuthenticatedProblemsProfileRoute: typeof AuthenticatedProblemsProfileRoute
  AuthenticatedTestsTestIdRoute: typeof AuthenticatedTestsTestIdRoute
  AuthenticatedProblemsIndexRoute: typeof AuthenticatedProblemsIndexRoute
  AuthenticatedTestsIndexRoute: typeof AuthenticatedTestsIndexRoute
  AuthenticatedProblemsContestsSlugRoute: typeof AuthenticatedProblemsContestsSlugRoute
  AuthenticatedProblemsPlansSlugRoute: typeof AuthenticatedProblemsPlansSlugRoute
  AuthenticatedProblemsContestsIndexRoute: typeof AuthenticatedProblemsContestsIndexRoute
  AuthenticatedProblemsPlansIndexRoute: typeof AuthenticatedProblemsPlansIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuthoringRoute: AuthenticatedAuthoringRoute,
  AuthenticatedBatchesRoute: AuthenticatedBatchesRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedCodingRoute: AuthenticatedCodingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvaluateRoute: AuthenticatedEvaluateRoute,
  AuthenticatedGradebookRoute: AuthenticatedGradebookRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedMyScoresRoute: AuthenticatedMyScoresRoute,
  AuthenticatedPlaygroundRoute: AuthenticatedPlaygroundRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
  AuthenticatedReadinessRoute: AuthenticatedReadinessRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedProblemsSlugRoute: AuthenticatedProblemsSlugRoute,
  AuthenticatedProblemsProfileRoute: AuthenticatedProblemsProfileRoute,
  AuthenticatedTestsTestIdRoute: AuthenticatedTestsTestIdRoute,
  AuthenticatedProblemsIndexRoute: AuthenticatedProblemsIndexRoute,
  AuthenticatedTestsIndexRoute: AuthenticatedTestsIndexRoute,
  AuthenticatedProblemsContestsSlugRoute:
    AuthenticatedProblemsContestsSlugRoute,
  AuthenticatedProblemsPlansSlugRoute: AuthenticatedProblemsPlansSlugRoute,
  AuthenticatedProblemsContestsIndexRoute:
    AuthenticatedProblemsContestsIndexRoute,
  AuthenticatedProblemsPlansIndexRoute: AuthenticatedProblemsPlansIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  VerifyRoute: VerifyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
