INSERT INTO public.practice_problems
(slug, title, level, category, company, tags, points, platform, sort_order, statement, constraints, examples, hints, solution, starter_code, test_cases)
VALUES
('climbing-stairs','Climbing Stairs','easy','Dynamic Programming','Amazon',ARRAY['Dynamic Programming','Recursion'],2,'internal',115,
 'You may climb 1 or 2 steps at a time. Given n, print the number of distinct ways to reach the top of a staircase with n steps.',
 '1 <= n <= 45',
 '[{"input":"5","output":"8","explanation":"There are eight orderings of 1 and 2 steps that total 5."}]'::jsonb,
 '["Ways(n) depends only on Ways(n-1) and Ways(n-2).","That is the Fibonacci recurrence.","Iterate bottom up with two rolling variables instead of recursion."]'::jsonb,
 'Bottom-up Fibonacci with two variables. Time O(n), space O(1).',
 '{"python":"import sys\nn = int(sys.stdin.read().split()[0])\n# print the number of ways\n","javascript":"const n = Number(require(\"fs\").readFileSync(0, \"utf8\").trim());\n// print the number of ways\n"}'::jsonb,
 '[{"input":"5","expected_output":"8","hidden":false},{"input":"2","expected_output":"2","hidden":false},{"input":"1","expected_output":"1","hidden":true},{"input":"10","expected_output":"89","hidden":true}]'::jsonb),

('house-robber','House Robber','medium','Dynamic Programming','Microsoft',ARRAY['Dynamic Programming','Arrays'],4,'internal',116,
 'The first line has n, the second line has n non-negative amounts. You may not take two adjacent amounts. Print the maximum total you can take.',
 '1 <= n <= 200000 and 0 <= amount <= 10000',
 '[{"input":"5\n2 7 9 3 1","output":"12","explanation":"Take 2, 9 and 1."}]'::jsonb,
 '["At each house you either skip it or take it and skip the previous one.","best[i] = max(best[i-1], best[i-2] + value[i]).","Only the last two results are needed."]'::jsonb,
 'Linear DP with two rolling variables for the previous two answers. Time O(n), space O(1).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nnums = data[1:1+data[0]]\n# print the maximum total\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst nums = data.slice(1, 1 + data[0]);\n// print the maximum total\n"}'::jsonb,
 '[{"input":"5\n2 7 9 3 1","expected_output":"12","hidden":false},{"input":"4\n2 1 1 2","expected_output":"4","hidden":false},{"input":"1\n5","expected_output":"5","hidden":true},{"input":"4\n1 2 3 1","expected_output":"4","hidden":true}]'::jsonb),

('coin-change-min','Minimum Coins','medium','Dynamic Programming','Goldman Sachs',ARRAY['Dynamic Programming','Greedy'],4,'internal',117,
 'The first line has the number of coin types m and the amount a. The second line has m coin values, each usable any number of times. Print the fewest coins that make exactly a, or -1 when it is impossible.',
 '1 <= m <= 50, 0 <= a <= 10000',
 '[{"input":"3 11\n1 2 5","output":"3","explanation":"5 + 5 + 1."}]'::jsonb,
 '["Greedy by largest coin is wrong for arbitrary coin sets.","Build the answer for every amount from 0 up to a.","best[x] = 1 + min(best[x - coin]) over usable coins."]'::jsonb,
 'Unbounded knapsack DP over amounts. Time O(m * a), space O(a).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nm, a = data[0], data[1]\ncoins = data[2:2+m]\n# print the fewest coins or -1\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst m = data[0], a = data[1], coins = data.slice(2, 2 + m);\n// print the fewest coins or -1\n"}'::jsonb,
 '[{"input":"3 11\n1 2 5","expected_output":"3","hidden":false},{"input":"1 3\n2","expected_output":"-1","hidden":false},{"input":"1 0\n1","expected_output":"0","hidden":true},{"input":"3 6\n1 3 4","expected_output":"2","hidden":true}]'::jsonb),

('longest-common-subsequence','Longest Common Subsequence','hard','Dynamic Programming','Oracle',ARRAY['Dynamic Programming','Strings'],5,'internal',118,
 'Two lowercase strings are given on separate lines. Print the length of their longest common subsequence (characters in order, not necessarily contiguous).',
 '1 <= length of each string <= 1000',
 '[{"input":"abcde\nace","output":"3","explanation":"ace appears in order inside abcde."}]'::jsonb,
 '["Compare the two strings character by character with a 2D table.","If the characters match, extend the diagonal answer by one.","Otherwise take the better of dropping one character from either string."]'::jsonb,
 'Classic 2D DP table of size (n+1) x (m+1). Time O(n*m), space O(min(n,m)) with a rolling row.',
 '{"python":"import sys\na, b = sys.stdin.read().split()\n# print the LCS length\n","javascript":"const [a, b] = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean);\n// print the LCS length\n"}'::jsonb,
 '[{"input":"abcde\nace","expected_output":"3","hidden":false},{"input":"abc\ndef","expected_output":"0","hidden":false},{"input":"abc\nabc","expected_output":"3","hidden":true},{"input":"aggtab\ngxtxayb","expected_output":"4","hidden":true}]'::jsonb),

('edit-distance','Edit Distance','hard','Dynamic Programming','Google',ARRAY['Dynamic Programming','Strings'],5,'internal',119,
 'Two lowercase words are given on separate lines. Print the minimum number of single character insertions, deletions or replacements that turn the first word into the second.',
 '1 <= length of each word <= 1000',
 '[{"input":"horse\nros","output":"3","explanation":"Replace h with r, delete r, delete e."}]'::jsonb,
 '["Fill a table where cell (i, j) is the cost for the first i and first j characters.","Matching characters cost nothing and move diagonally.","Otherwise take one plus the best of insert, delete or replace."]'::jsonb,
 'Levenshtein DP over a (n+1) x (m+1) grid. Time O(n*m).',
 '{"python":"import sys\na, b = sys.stdin.read().split()\n# print the edit distance\n","javascript":"const [a, b] = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean);\n// print the edit distance\n"}'::jsonb,
 '[{"input":"horse\nros","expected_output":"3","hidden":false},{"input":"intention\nexecution","expected_output":"5","hidden":false},{"input":"abc\nabc","expected_output":"0","hidden":true},{"input":"sunday\nsaturday","expected_output":"3","hidden":true}]'::jsonb),

('count-islands','Count the Islands','hard','Graphs','Amazon',ARRAY['Graphs','DFS','Matrix'],5,'internal',120,
 'The first line has r and c. The next r lines each contain a string of c characters that are 0 (water) or 1 (land). Print how many islands there are; cells connect horizontally and vertically only.',
 '1 <= r, c <= 500',
 '[{"input":"4 5\n11000\n11000\n00100\n00011","output":"3","explanation":"Three separate groups of land."}]'::jsonb,
 '["Every unvisited land cell starts a new island.","Flood fill it with DFS or BFS and mark cells visited.","Count how many flood fills you start."]'::jsonb,
 'Iterate all cells; each unvisited 1 triggers a flood fill and increments the island count. Time O(r*c).',
 '{"python":"import sys\nlines = sys.stdin.read().split()\nr, c = int(lines[0]), int(lines[1])\ngrid = lines[2:2+r]\n# print the number of islands\n","javascript":"const t = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean);\nconst r = Number(t[0]), c = Number(t[1]), grid = t.slice(2, 2 + r);\n// print the number of islands\n"}'::jsonb,
 '[{"input":"4 5\n11000\n11000\n00100\n00011","expected_output":"3","hidden":false},{"input":"2 2\n10\n01","expected_output":"2","hidden":false},{"input":"1 1\n0","expected_output":"0","hidden":true},{"input":"3 3\n111\n111\n111","expected_output":"1","hidden":true}]'::jsonb),

('graph-shortest-path','Shortest Path in an Unweighted Graph','hard','Graphs','Flipkart',ARRAY['Graphs','BFS'],5,'internal',121,
 'The first line has n nodes and m edges. The next m lines each have two node labels of an undirected edge. The last line has the source s and the destination t. Nodes are labelled 1..n. Print the fewest edges from s to t, or -1 when t is unreachable.',
 '1 <= n <= 100000 and 0 <= m <= 200000',
 '[{"input":"6 6\n1 2\n2 3\n3 4\n1 5\n5 6\n6 4\n1 4","output":"3","explanation":"1-2-3-4 uses three edges."}]'::jsonb,
 '["All edges cost the same, so BFS gives the shortest path.","Store the graph as adjacency lists.","Record the distance the first time a node is reached."]'::jsonb,
 'Breadth-first search from the source, recording distances on first visit. Time O(n + m).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nn, m = data[0], data[1]\nedges = data[2:2+2*m]\ns, t = data[2+2*m], data[3+2*m]\n# print the shortest number of edges or -1\n","javascript":"const d = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = d[0], m = d[1], edges = d.slice(2, 2 + 2 * m);\nconst s = d[2 + 2 * m], t = d[3 + 2 * m];\n// print the shortest number of edges or -1\n"}'::jsonb,
 '[{"input":"6 6\n1 2\n2 3\n3 4\n1 5\n5 6\n6 4\n1 4","expected_output":"3","hidden":false},{"input":"2 0\n1 2","expected_output":"-1","hidden":false},{"input":"2 1\n1 2\n1 2","expected_output":"1","hidden":true},{"input":"3 1\n1 2\n2 2","expected_output":"0","hidden":true}]'::jsonb),

('detect-cycle-undirected','Detect a Cycle','medium','Graphs','Cognizant',ARRAY['Graphs','DFS','Union Find'],4,'internal',122,
 'The first line has n nodes and m edges, followed by m lines each with an undirected edge. Nodes are labelled 1..n. Print YES when the graph contains a cycle, otherwise NO.',
 '1 <= n <= 100000 and 0 <= m <= 200000',
 '[{"input":"3 3\n1 2\n2 3\n3 1","output":"YES","explanation":"The three edges form a triangle."}]'::jsonb,
 '["A cycle exists when an edge reaches an already visited node that is not the parent.","DFS with a parent argument works.","Union-Find is an alternative: an edge inside one component means a cycle."]'::jsonb,
 'DFS keeping the parent, or Union-Find merging endpoints. Time O(n + m).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nn, m = data[0], data[1]\nedges = data[2:2+2*m]\n# print YES or NO\n","javascript":"const d = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = d[0], m = d[1], edges = d.slice(2, 2 + 2 * m);\n// print YES or NO\n"}'::jsonb,
 '[{"input":"3 3\n1 2\n2 3\n3 1","expected_output":"YES","hidden":false},{"input":"3 2\n1 2\n2 3","expected_output":"NO","hidden":false},{"input":"1 0","expected_output":"NO","hidden":true},{"input":"4 4\n1 2\n2 3\n3 1\n3 4","expected_output":"YES","hidden":true}]'::jsonb),

('count-set-bits','Count the Set Bits','easy','Bit Manipulation','Qualcomm',ARRAY['Bit Manipulation','Math'],1,'internal',123,
 'Given a non-negative integer n, print how many 1 bits its binary representation contains.',
 '0 <= n <= 10^18',
 '[{"input":"13","output":"3","explanation":"13 is 1101 in binary."}]'::jsonb,
 '["Check the lowest bit with n & 1, then shift right.","n & (n - 1) clears the lowest set bit.","Counting with that trick runs once per set bit."]'::jsonb,
 'Repeatedly apply n &= n - 1 and count the iterations. Time O(number of set bits).',
 '{"python":"import sys\nn = int(sys.stdin.read().split()[0])\n# print the number of set bits\n","javascript":"const n = BigInt(require(\"fs\").readFileSync(0, \"utf8\").trim());\n// print the number of set bits\n"}'::jsonb,
 '[{"input":"13","expected_output":"3","hidden":false},{"input":"0","expected_output":"0","hidden":false},{"input":"255","expected_output":"8","hidden":true},{"input":"1024","expected_output":"1","hidden":true}]'::jsonb),

('single-number','The Lonely Number','medium','Bit Manipulation','Adobe',ARRAY['Bit Manipulation','Hashing'],3,'internal',124,
 'The first line has n, the second line has n integers in which every value appears exactly twice except one. Print the value that appears once.',
 '1 <= n <= 200000 and n is odd',
 '[{"input":"5\n4 1 2 1 2","output":"4","explanation":"Only 4 is unpaired."}]'::jsonb,
 '["A hash map works but uses extra memory.","x XOR x is 0 and x XOR 0 is x.","XOR the whole array together."]'::jsonb,
 'XOR every element; pairs cancel and the lonely value remains. Time O(n), space O(1).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nnums = data[1:1+data[0]]\n# print the value that appears once\n","javascript":"const d = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst nums = d.slice(1, 1 + d[0]);\n// print the value that appears once\n"}'::jsonb,
 '[{"input":"5\n4 1 2 1 2","expected_output":"4","hidden":false},{"input":"1\n7","expected_output":"7","hidden":false},{"input":"3\n2 2 9","expected_output":"9","hidden":true},{"input":"7\n1 1 2 2 3 3 5","expected_output":"5","hidden":true}]'::jsonb),

('activity-selection','Activity Selection','medium','Greedy','Deloitte',ARRAY['Greedy','Sorting'],4,'internal',125,
 'The first line has n. Each of the next n lines has the start and end time of an activity. Print the maximum number of activities one person can attend; an activity may start exactly when another ends.',
 '1 <= n <= 100000 and 0 <= start < end <= 10^9',
 '[{"input":"6\n1 2\n3 4\n0 6\n5 7\n8 9\n5 9","output":"4","explanation":"Attend (1,2), (3,4), (5,7) and (8,9)."}]'::jsonb,
 '["Sorting by start time is not optimal.","Sort by finishing time instead.","Greedily take an activity whenever it starts at or after the last chosen end."]'::jsonb,
 'Sort by end time and greedily accept compatible activities. Time O(n log n).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nn = data[0]\npairs = [(data[1+2*i], data[2+2*i]) for i in range(n)]\n# print how many activities fit\n","javascript":"const d = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = d[0];\nconst pairs = Array.from({ length: n }, (_, i) => [d[1 + 2 * i], d[2 + 2 * i]]);\n// print how many activities fit\n"}'::jsonb,
 '[{"input":"6\n1 2\n3 4\n0 6\n5 7\n8 9\n5 9","expected_output":"4","hidden":false},{"input":"2\n1 5\n2 6","expected_output":"1","hidden":false},{"input":"1\n5 10","expected_output":"1","hidden":true},{"input":"3\n1 10\n2 3\n3 4","expected_output":"2","hidden":true}]'::jsonb),

('merge-intervals','Merge Intervals','medium','Sorting','Salesforce',ARRAY['Sorting','Arrays'],4,'internal',126,
 'The first line has n. Each of the next n lines has an interval start and end. Print the merged, non-overlapping intervals in increasing order, one per line as "start end"; touching intervals merge.',
 '1 <= n <= 100000',
 '[{"input":"4\n1 3\n2 6\n8 10\n15 18","output":"1 6\n8 10\n15 18","explanation":"1-3 and 2-6 overlap."}]'::jsonb,
 '["Sort the intervals by start.","Keep the current merged interval and extend its end when the next start is not beyond it.","Otherwise emit it and begin a new one."]'::jsonb,
 'Sort by start, then sweep merging overlaps. Time O(n log n).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nn = data[0]\nivs = [(data[1+2*i], data[2+2*i]) for i in range(n)]\n# print each merged interval on its own line\n","javascript":"const d = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = d[0];\nconst ivs = Array.from({ length: n }, (_, i) => [d[1 + 2 * i], d[2 + 2 * i]]);\n// print each merged interval on its own line\n"}'::jsonb,
 '[{"input":"4\n1 3\n2 6\n8 10\n15 18","expected_output":"1 6\n8 10\n15 18","hidden":false},{"input":"2\n1 4\n4 5","expected_output":"1 5","hidden":false},{"input":"1\n3 7","expected_output":"3 7","hidden":true},{"input":"3\n5 6\n1 2\n3 4","expected_output":"1 2\n3 4\n5 6","hidden":true}]'::jsonb),

('kth-largest','Kth Largest Element','medium','Sorting','Uber',ARRAY['Sorting','Heap'],4,'internal',127,
 'The first line has n and k. The second line has n integers, duplicates allowed. Print the kth largest value when the values are ordered from largest to smallest.',
 '1 <= k <= n <= 200000',
 '[{"input":"6 2\n3 2 1 5 6 4","output":"5","explanation":"Sorted descending gives 6 5 4 3 2 1."}]'::jsonb,
 '["Sorting the whole array is the simplest correct answer.","A min-heap of size k is faster when k is small.","Duplicates count as separate positions."]'::jsonb,
 'Sort descending and index k-1, or keep a size-k min-heap. Time O(n log n) or O(n log k).',
 '{"python":"import sys\nd = list(map(int, sys.stdin.read().split()))\nn, k = d[0], d[1]\nnums = d[2:2+n]\n# print the kth largest value\n","javascript":"const d = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = d[0], k = d[1], nums = d.slice(2, 2 + n);\n// print the kth largest value\n"}'::jsonb,
 '[{"input":"6 2\n3 2 1 5 6 4","expected_output":"5","hidden":false},{"input":"4 2\n7 7 3 1","expected_output":"7","hidden":false},{"input":"1 1\n9","expected_output":"9","hidden":true},{"input":"5 5\n1 2 3 4 5","expected_output":"1","hidden":true}]'::jsonb),

('rotate-array-k','Rotate the Array','medium','Arrays','Wipro',ARRAY['Arrays','Two Pointers'],3,'internal',128,
 'The first line has n and k. The second line has n integers. Print the array rotated to the right by k positions, space separated. k may exceed n.',
 '1 <= n <= 200000 and 0 <= k <= 10^9',
 '[{"input":"7 3\n1 2 3 4 5 6 7","output":"5 6 7 1 2 3 4","explanation":"The last three values move to the front."}]'::jsonb,
 '["Reduce k with k mod n first.","Slicing gives a one line solution.","The in-place trick is to reverse the whole array, then each part."]'::jsonb,
 'Take k modulo n, then output the tail followed by the head. Time O(n).',
 '{"python":"import sys\nd = list(map(int, sys.stdin.read().split()))\nn, k = d[0], d[1]\nnums = d[2:2+n]\n# print the rotated array space separated\n","javascript":"const d = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = d[0], k = d[1], nums = d.slice(2, 2 + n);\n// print the rotated array space separated\n"}'::jsonb,
 '[{"input":"7 3\n1 2 3 4 5 6 7","expected_output":"5 6 7 1 2 3 4","hidden":false},{"input":"3 0\n1 2 3","expected_output":"1 2 3","hidden":false},{"input":"3 4\n1 2 3","expected_output":"3 1 2","hidden":true},{"input":"2 2\n9 8","expected_output":"9 8","hidden":true}]'::jsonb),

('matrix-spiral','Spiral Order of a Matrix','medium','Matrix','TCS',ARRAY['Matrix','Implementation'],4,'internal',129,
 'The first line has r and c. The next r lines each have c integers. Print all values in clockwise spiral order starting from the top-left, space separated on one line.',
 '1 <= r, c <= 500',
 '[{"input":"3 3\n1 2 3\n4 5 6\n7 8 9","output":"1 2 3 6 9 8 7 4 5","explanation":"Walk the outer ring, then the centre."}]'::jsonb,
 '["Track four boundaries: top, bottom, left and right.","After walking a row or column, move that boundary inwards.","Stop as soon as the boundaries cross."]'::jsonb,
 'Shrink four boundaries while emitting the top row, right column, bottom row and left column in turn. Time O(r*c).',
 '{"python":"import sys\nd = list(map(int, sys.stdin.read().split()))\nr, c = d[0], d[1]\ngrid = [d[2+i*c:2+(i+1)*c] for i in range(r)]\n# print the spiral order space separated\n","javascript":"const d = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst r = d[0], c = d[1];\nconst grid = Array.from({ length: r }, (_, i) => d.slice(2 + i * c, 2 + (i + 1) * c));\n// print the spiral order space separated\n"}'::jsonb,
 '[{"input":"3 3\n1 2 3\n4 5 6\n7 8 9","expected_output":"1 2 3 6 9 8 7 4 5","hidden":false},{"input":"2 3\n1 2 3\n4 5 6","expected_output":"1 2 3 6 5 4","hidden":false},{"input":"1 4\n1 2 3 4","expected_output":"1 2 3 4","hidden":true},{"input":"4 1\n1\n2\n3\n4","expected_output":"1 2 3 4","hidden":true}]'::jsonb)
ON CONFLICT (slug) DO NOTHING;