INSERT INTO public.practice_problems
(slug, title, level, category, company, tags, points, platform, sort_order, statement, constraints, examples, hints, solution, starter_code, test_cases)
VALUES
('count-vowels','Count the Vowels','easy','Strings','TCS',ARRAY['Strings','Implementation'],1,'internal',100,
 'Given a lowercase word, print how many of its characters are vowels (a, e, i, o, u).',
 '1 <= length of the word <= 10000',
 '[{"input":"training","output":"3","explanation":"a, i and i are vowels."}]'::jsonb,
 '["Loop over the characters one by one.","Keep a set of the five vowels for O(1) membership tests.","Increment a counter whenever the character is in that set."]'::jsonb,
 'Walk the string once and count characters that belong to the vowel set. Time O(n), space O(1).',
 '{"python":"import sys\ns = sys.stdin.read().strip()\n# print the number of vowels\n","javascript":"const s = require(\"fs\").readFileSync(0, \"utf8\").trim();\n// print the number of vowels\n"}'::jsonb,
 '[{"input":"training","expected_output":"3","hidden":false},{"input":"rhythm","expected_output":"0","hidden":false},{"input":"aeiou","expected_output":"5","hidden":true},{"input":"placementready","expected_output":"5","hidden":true}]'::jsonb),

('largest-in-array','Largest in the Array','easy','Arrays','Infosys',ARRAY['Arrays','Implementation'],1,'internal',101,
 'The first line has n. The second line has n integers. Print the largest of them.',
 '1 <= n <= 100000 and each value fits in a 32-bit integer',
 '[{"input":"5\n3 9 2 9 -4","output":"9","explanation":"9 is the maximum."}]'::jsonb,
 '["Read every number before deciding.","Track a running maximum starting from the first element.","Do not initialise the maximum with 0 — values can be negative."]'::jsonb,
 'Scan once, keeping the best value seen so far. Time O(n), space O(1).',
 '{"python":"import sys\ndata = sys.stdin.read().split()\nn = int(data[0])\nnums = list(map(int, data[1:1+n]))\n# print the largest value\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = data[0], nums = data.slice(1, 1 + n);\n// print the largest value\n"}'::jsonb,
 '[{"input":"5\n3 9 2 9 -4","expected_output":"9","hidden":false},{"input":"3\n-7 -2 -9","expected_output":"-2","hidden":false},{"input":"1\n42","expected_output":"42","hidden":true},{"input":"6\n1 2 3 4 5 6","expected_output":"6","hidden":true}]'::jsonb),

('second-largest','Second Largest Value','easy','Arrays','Wipro',ARRAY['Arrays','Sorting'],2,'internal',102,
 'The first line has n, the second line has n integers. Print the second largest distinct value, or -1 when it does not exist.',
 '1 <= n <= 100000',
 '[{"input":"5\n4 8 8 1 6","output":"6","explanation":"Distinct values are 1, 4, 6, 8 so the runner-up is 6."}]'::jsonb,
 '["Duplicates of the maximum do not count as the runner-up.","Keep two variables: best and second best.","Update second best only when the value is strictly smaller than best."]'::jsonb,
 'Track the best and the second best distinct value in a single pass. Time O(n), space O(1).',
 '{"python":"import sys\ndata = sys.stdin.read().split()\nn = int(data[0])\nnums = list(map(int, data[1:1+n]))\n# print the second largest distinct value or -1\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst nums = data.slice(1, 1 + data[0]);\n// print the second largest distinct value or -1\n"}'::jsonb,
 '[{"input":"5\n4 8 8 1 6","expected_output":"6","hidden":false},{"input":"3\n5 5 5","expected_output":"-1","hidden":false},{"input":"2\n1 2","expected_output":"1","hidden":true},{"input":"1\n9","expected_output":"-1","hidden":true}]'::jsonb),

('gcd-of-two','GCD of Two Numbers','easy','Math','Capgemini',ARRAY['Math','Recursion'],1,'internal',103,
 'Two integers a and b are given on separate lines. Print their greatest common divisor.',
 '1 <= a, b <= 1000000000',
 '[{"input":"12\n18","output":"6","explanation":"6 divides both 12 and 18."}]'::jsonb,
 '["Trial division up to min(a, b) is too slow for large inputs.","Euclid: gcd(a, b) = gcd(b, a mod b).","The recursion stops when b becomes 0."]'::jsonb,
 'Apply the Euclidean algorithm repeatedly until the remainder is zero. Time O(log min(a,b)).',
 '{"python":"import sys\na, b = map(int, sys.stdin.read().split())\n# print gcd(a, b)\n","javascript":"const [a, b] = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\n// print gcd(a, b)\n"}'::jsonb,
 '[{"input":"12\n18","expected_output":"6","hidden":false},{"input":"7\n13","expected_output":"1","hidden":false},{"input":"1000000000\n2","expected_output":"2","hidden":true},{"input":"270\n192","expected_output":"6","hidden":true}]'::jsonb),

('palindrome-number','Palindrome Number','easy','Math','Accenture',ARRAY['Math','Strings'],1,'internal',104,
 'Given a non-negative integer, print YES when it reads the same forwards and backwards, otherwise NO.',
 '0 <= n <= 10^18',
 '[{"input":"12321","output":"YES","explanation":"Reversed it is still 12321."}]'::jsonb,
 '["The digits can be compared as a string.","Or rebuild the number by repeatedly taking n % 10.","Single digit numbers are always palindromes."]'::jsonb,
 'Compare the decimal representation with its reverse. Time O(number of digits).',
 '{"python":"import sys\nn = sys.stdin.read().strip()\n# print YES or NO\n","javascript":"const n = require(\"fs\").readFileSync(0, \"utf8\").trim();\n// print YES or NO\n"}'::jsonb,
 '[{"input":"12321","expected_output":"YES","hidden":false},{"input":"1230","expected_output":"NO","hidden":false},{"input":"7","expected_output":"YES","hidden":true},{"input":"1000000000000000001","expected_output":"YES","hidden":true}]'::jsonb),

('anagram-check','Anagram Check','easy','Hashing','Cognizant',ARRAY['Hashing','Strings'],2,'internal',105,
 'Two lowercase words are given on separate lines. Print YES when one is a rearrangement of the other, otherwise NO.',
 '1 <= length of each word <= 100000',
 '[{"input":"listen\nsilent","output":"YES","explanation":"Both words use the same letters."}]'::jsonb,
 '["Different lengths can never be anagrams.","Count how often each letter appears.","Compare the two frequency tables."]'::jsonb,
 'Build a 26-slot frequency table for each word and compare them. Time O(n), space O(1).',
 '{"python":"import sys\na, b = sys.stdin.read().split()\n# print YES or NO\n","javascript":"const [a, b] = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean);\n// print YES or NO\n"}'::jsonb,
 '[{"input":"listen\nsilent","expected_output":"YES","hidden":false},{"input":"hello\nworld","expected_output":"NO","hidden":false},{"input":"a\na","expected_output":"YES","hidden":true},{"input":"aab\nabb","expected_output":"NO","hidden":true}]'::jsonb),

('first-unique-character','First Unique Character','medium','Hashing','Amazon',ARRAY['Hashing','Strings'],3,'internal',106,
 'Given a lowercase string, print the index of the first character that appears exactly once, or -1 when every character repeats. Indices start at 0.',
 '1 <= length of the string <= 200000',
 '[{"input":"crtcourse","output":"3","explanation":"o is the first character that never repeats."}]'::jsonb,
 '["A single pass cannot know the future — count first.","Store the frequency of every character.","Scan the string again and return the first index with frequency 1."]'::jsonb,
 'Two passes: build a frequency map, then find the earliest index whose count is one. Time O(n).',
 '{"python":"import sys\ns = sys.stdin.read().strip()\n# print the index or -1\n","javascript":"const s = require(\"fs\").readFileSync(0, \"utf8\").trim();\n// print the index or -1\n"}'::jsonb,
 '[{"input":"crtcourse","expected_output":"3","hidden":false},{"input":"aabb","expected_output":"-1","hidden":false},{"input":"z","expected_output":"0","hidden":true},{"input":"aabbc","expected_output":"4","hidden":true}]'::jsonb),

('pair-with-sum','Pair With Given Sum','medium','Hashing','TCS',ARRAY['Hashing','Arrays'],3,'internal',107,
 'The first line has n and the target t. The second line has n distinct integers. Print the 0-based indices i and j (i < j) of the unique pair that adds up to t, separated by a space. Print -1 when no pair exists.',
 '2 <= n <= 100000 and at most one valid pair exists',
 '[{"input":"4 9\n2 7 11 15","output":"0 1","explanation":"2 + 7 = 9."}]'::jsonb,
 '["The brute force pair loop is O(n^2) — too slow for n = 100000.","While scanning, ask whether t - value was already seen.","Store value to index in a dictionary as you go."]'::jsonb,
 'Keep a hash map of value to index; for each element check whether the complement is already stored. Time O(n).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nn, t = data[0], data[1]\nnums = data[2:2+n]\n# print the two indices or -1\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = data[0], t = data[1], nums = data.slice(2, 2 + n);\n// print the two indices or -1\n"}'::jsonb,
 '[{"input":"4 9\n2 7 11 15","expected_output":"0 1","hidden":false},{"input":"3 100\n1 2 3","expected_output":"-1","hidden":false},{"input":"5 -3\n-1 -2 4 8 9","expected_output":"0 1","hidden":true},{"input":"2 5\n2 3","expected_output":"0 1","hidden":true}]'::jsonb),

('move-zeroes','Move Zeroes to the End','medium','Two Pointers','Infosys',ARRAY['Two Pointers','Arrays'],3,'internal',108,
 'The first line has n, the second line has n integers. Print the same values space separated with every zero pushed to the end while the order of the non-zero values is preserved.',
 '1 <= n <= 100000',
 '[{"input":"6\n0 1 0 3 12 0","output":"1 3 12 0 0 0","explanation":"Non-zero order is kept, zeroes trail."}]'::jsonb,
 '["Use a write pointer for the next non-zero slot.","Copy each non-zero value to the write pointer and advance it.","Fill the remaining slots with zeroes."]'::jsonb,
 'A stable partition with two pointers: write non-zeroes forward, then pad with zeroes. Time O(n), space O(1).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nnums = data[1:1+data[0]]\n# print the rearranged values space separated\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst nums = data.slice(1, 1 + data[0]);\n// print the rearranged values space separated\n"}'::jsonb,
 '[{"input":"6\n0 1 0 3 12 0","expected_output":"1 3 12 0 0 0","hidden":false},{"input":"3\n1 2 3","expected_output":"1 2 3","hidden":false},{"input":"2\n0 0","expected_output":"0 0","hidden":true},{"input":"5\n0 0 5 0 7","expected_output":"5 7 0 0 0","hidden":true}]'::jsonb),

('max-water-container','Maximum Water Between Lines','medium','Two Pointers','Google',ARRAY['Two Pointers','Greedy'],4,'internal',109,
 'The first line has n heights count, the second line has n non-negative heights. Choosing two lines i and j, the water held is min(h[i], h[j]) * (j - i). Print the maximum water that can be held.',
 '2 <= n <= 200000 and 0 <= height <= 10000',
 '[{"input":"9\n1 8 6 2 5 4 8 3 7","output":"49","explanation":"Lines of height 8 and 7 are 7 apart."}]'::jsonb,
 '["Start with the widest pair: one pointer at each end.","The shorter line limits the area, so moving the taller one can never help.","Move the pointer at the shorter line inwards."]'::jsonb,
 'Two pointers from both ends, always advancing the shorter side, keeping the best area. Time O(n).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nh = data[1:1+data[0]]\n# print the maximum area\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst h = data.slice(1, 1 + data[0]);\n// print the maximum area\n"}'::jsonb,
 '[{"input":"9\n1 8 6 2 5 4 8 3 7","expected_output":"49","hidden":false},{"input":"2\n1 1","expected_output":"1","hidden":false},{"input":"4\n0 0 0 0","expected_output":"0","hidden":true},{"input":"5\n1 2 4 3 2","expected_output":"6","hidden":true}]'::jsonb),

('longest-unique-substring','Longest Substring Without Repeats','medium','Sliding Window','Microsoft',ARRAY['Sliding Window','Hashing','Strings'],4,'internal',110,
 'Given a lowercase string, print the length of the longest contiguous block in which no character repeats.',
 '1 <= length of the string <= 200000',
 '[{"input":"abcabcbb","output":"3","explanation":"abc has length 3."}]'::jsonb,
 '["Grow a window to the right while it stays valid.","When a repeat appears, shrink from the left.","Remember the last index of each character to jump the left edge."]'::jsonb,
 'Sliding window with a last-seen index per character; the window left edge jumps past the previous occurrence. Time O(n).',
 '{"python":"import sys\ns = sys.stdin.read().strip()\n# print the longest length\n","javascript":"const s = require(\"fs\").readFileSync(0, \"utf8\").trim();\n// print the longest length\n"}'::jsonb,
 '[{"input":"abcabcbb","expected_output":"3","hidden":false},{"input":"bbbbb","expected_output":"1","hidden":false},{"input":"pwwkew","expected_output":"3","hidden":true},{"input":"abcdefg","expected_output":"7","hidden":true}]'::jsonb),

('max-subarray-sum','Maximum Subarray Sum','medium','Dynamic Programming','Adobe',ARRAY['Dynamic Programming','Arrays'],4,'internal',111,
 'The first line has n, the second line has n integers. Print the largest sum obtainable from a contiguous non-empty block.',
 '1 <= n <= 200000 and values may be negative',
 '[{"input":"9\n-2 1 -3 4 -1 2 1 -5 4","output":"6","explanation":"The block 4 -1 2 1 sums to 6."}]'::jsonb,
 '["Ask at each index: extend the previous block or start fresh?","best_here = max(value, best_here + value).","Track the overall best separately."]'::jsonb,
 'Kadane algorithm: keep the best sum ending here and the best sum overall. Time O(n), space O(1).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nnums = data[1:1+data[0]]\n# print the maximum subarray sum\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst nums = data.slice(1, 1 + data[0]);\n// print the maximum subarray sum\n"}'::jsonb,
 '[{"input":"9\n-2 1 -3 4 -1 2 1 -5 4","expected_output":"6","hidden":false},{"input":"3\n-5 -2 -9","expected_output":"-2","hidden":false},{"input":"1\n7","expected_output":"7","hidden":true},{"input":"5\n2 2 2 2 2","expected_output":"10","hidden":true}]'::jsonb),

('valid-parentheses','Valid Parentheses','easy','Stack','Zoho',ARRAY['Stack','Strings'],2,'internal',112,
 'A string made only of the characters ()[]{} is given. Print YES when every bracket is closed by the matching type in the correct order, otherwise NO.',
 '1 <= length of the string <= 100000',
 '[{"input":"{[()]}","output":"YES","explanation":"Every bracket closes in order."}]'::jsonb,
 '["Push opening brackets on a stack.","A closing bracket must match the top of the stack.","The stack must be empty at the end."]'::jsonb,
 'Use a stack of expected closers; mismatch or leftovers mean the string is invalid. Time O(n).',
 '{"python":"import sys\ns = sys.stdin.read().strip()\n# print YES or NO\n","javascript":"const s = require(\"fs\").readFileSync(0, \"utf8\").trim();\n// print YES or NO\n"}'::jsonb,
 '[{"input":"{[()]}","expected_output":"YES","hidden":false},{"input":"([)]","expected_output":"NO","hidden":false},{"input":"(((","expected_output":"NO","hidden":true},{"input":"()[]{}","expected_output":"YES","hidden":true}]'::jsonb),

('next-greater-element','Next Greater Element','medium','Stack','Flipkart',ARRAY['Stack','Arrays'],4,'internal',113,
 'The first line has n, the second line has n integers. For every position print the first value to its right that is strictly greater, or -1 when there is none. Print the answers space separated on one line.',
 '1 <= n <= 200000',
 '[{"input":"4\n4 5 2 25","output":"5 25 25 -1","explanation":"25 has nothing greater to its right."}]'::jsonb,
 '["The naive double loop is O(n^2).","Scan from the right with a stack of candidates.","Pop everything not greater than the current value."]'::jsonb,
 'Monotonic decreasing stack scanned right to left; the stack top is the answer. Time O(n).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nnums = data[1:1+data[0]]\n# print the answers space separated\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst nums = data.slice(1, 1 + data[0]);\n// print the answers space separated\n"}'::jsonb,
 '[{"input":"4\n4 5 2 25","expected_output":"5 25 25 -1","hidden":false},{"input":"3\n3 2 1","expected_output":"-1 -1 -1","hidden":false},{"input":"1\n5","expected_output":"-1","hidden":true},{"input":"5\n1 3 2 4 2","expected_output":"3 4 4 -1 -1","hidden":true}]'::jsonb),

('binary-search-index','Binary Search Index','easy','Binary Search','Infosys',ARRAY['Binary Search','Arrays'],2,'internal',114,
 'The first line has n and the target t. The second line has n integers sorted in ascending order. Print the 0-based index of t, or -1 when it is absent. Values are distinct.',
 '1 <= n <= 500000',
 '[{"input":"5 7\n1 3 5 7 9","output":"3","explanation":"7 sits at index 3."}]'::jsonb,
 '["The array is sorted, so halve the search space each step.","Use low and high pointers and compare with the middle value.","Beware of an infinite loop — always move low or high past mid."]'::jsonb,
 'Classic binary search with inclusive bounds. Time O(log n).',
 '{"python":"import sys\ndata = list(map(int, sys.stdin.read().split()))\nn, t = data[0], data[1]\nnums = data[2:2+n]\n# print the index or -1\n","javascript":"const data = require(\"fs\").readFileSync(0, \"utf8\").split(/\\s+/).filter(Boolean).map(Number);\nconst n = data[0], t = data[1], nums = data.slice(2, 2 + n);\n// print the index or -1\n"}'::jsonb,
 '[{"input":"5 7\n1 3 5 7 9","expected_output":"3","hidden":false},{"input":"4 6\n1 2 3 4","expected_output":"-1","hidden":false},{"input":"1 1\n1","expected_output":"0","hidden":true},{"input":"6 11\n2 4 6 8 10 11","expected_output":"5","hidden":true}]'::jsonb)
ON CONFLICT (slug) DO NOTHING;